name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read out version and call discord webhook
        run: |
          echo Read out version and call discord webhook
          echo should probably be split up
